name: StopBuggingme
favicon: null
layout_spectrum: 0.8519575363025069
typography_spectrum: 0.713600676972419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.30768879665993154
  lightness: 0.6346740934532136
  saturation: 0.2581745027564466
  rhythmicContrast: 0.8616549393627793
purpose: []
