name: STOP Bugging ME
favicon: null
layout_spectrum: 0.8519575363025069
typography_spectrum: 0.713600676972419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#009200'
    - '#919191'
    - '#8bd58d'
  brandStrength: 0.30768879665993154
  lightness: 0.6346740934532136
  saturation: 0.2581745027564466
  rhythmicContrast: 0.8616549393627793
purpose: []
